language: python
python:
  - "3.7"
before_install:
  - sudo wget -O ffmpeg.tar.gz https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz
  - sudo mkdir ffmpeg
  - sudo tar xvf ffmpeg.tar.gz -C ffmpeg --strip-components=1
  - sudo cp ffmpeg/ffmpeg /usr/bin/
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - python test/test.py